AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create EventBus/EventRule for Spoke Account'
Parameters:
  HubAccount:
    Type: 'String'
    Default: '235431990733'
  HubEventBusName:
    Type: 'String'
    Default: 'CentralizedHubEventbus'    

Resources:
  EC2SpokeRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Event Rule to send message to HUB EventBus
      EventBusName: default
      Targets:
        - Arn: !Sub arn:aws:events:${AWS::Region}:${HubAccount}:event-bus/${HubEventBusName}
          Id: target-id1
          RoleArn: !GetAtt SlackManageRoleEventRule.Arn
      EventPattern:
        {
          "source": [
            "aws.ec2"
          ],
          "detail-type": [
            "AWS API Call via CloudTrail"
          ],
          "detail": {
            "eventSource": [
              "ec2.amazonaws.com"
            ],
            "eventName": [
              "RunInstances"
            ]
          }
        }

  RDSSpokeRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Event Rule to send message to HUB EventBus
      EventBusName: default
      Targets:
        - Arn: !Sub arn:aws:events:${AWS::Region}:${HubAccount}:event-bus/${HubEventBusName}
          Id: target-id1
          RoleArn: !GetAtt SlackManageRoleEventRule.Arn
      EventPattern:
        {
          "source": [
            "aws.rds"
          ],
          "detail-type": [
            "AWS API Call via CloudTrail"
          ],
          "detail": {
            "eventSource": [
              "rds.amazonaws.com"
            ],
            "eventName": [
              "CreateDBInstance"
            ]
          }
        } 

  ECSSpokeRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Event Rule to send message to HUB EventBus
      EventBusName: default
      Targets:
        - Arn: !Sub arn:aws:events:${AWS::Region}:${HubAccount}:event-bus/${HubEventBusName}
          Id: target-id1
          RoleArn: !GetAtt SlackManageRoleEventRule.Arn
      EventPattern:
        {
          "source": [
            "aws.ecs"
          ],
          "detail-type": [
            "AWS API Call via CloudTrail"
          ],
          "detail": {
            "eventSource": [
              "ecs.amazonaws.com"
            ],
            "eventName": [
              "CreateCluster"
            ]
          }
        }  

  ElastiCacheSpokeRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Event Rule to send message to HUB EventBus
      EventBusName: default
      Targets:
        - Arn: !Sub arn:aws:events:${AWS::Region}:${HubAccount}:event-bus/${HubEventBusName}
          Id: target-id1
          RoleArn: !GetAtt SlackManageRoleEventRule.Arn
      EventPattern:
        {
          "source": [
            "aws.elasticache"
          ],
          "detail-type": [
            "AWS API Call via CloudTrail"
          ],
          "detail": {
            "eventSource": [
              "elasticache.amazonaws.com"
            ],
            "eventName": [
              "CreateReplicationGroup"
            ]
          }
        } 

  ElasticsearchSpokeRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Event Rule to send message to HUB EventBus
      EventBusName: default
      Targets:
        - Arn: !Sub arn:aws:events:${AWS::Region}:${HubAccount}:event-bus/${HubEventBusName}
          Id: target-id1
          RoleArn: !GetAtt SlackManageRoleEventRule.Arn
      EventPattern:
        {
          "source": [
            "aws.es"
          ],
          "detail-type": [
            "AWS API Call via CloudTrail"
          ],
          "detail": {
            "eventSource": [
              "es.amazonaws.com"
            ],
            "eventName": [
              "CreateElasticsearchDomain"
            ]
          }
        }         

  SlackManageRoleEventRule: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - events.amazonaws.com
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - !Ref SlackUpdateManagePolicy

  SlackUpdateManagePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: 'Customer Managed Policy For Slack Automation'
      Path: / 
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Sid: AllowAutomation 
            Effect: Allow
            Action: 
              - iam:PassRole
            Resource:
              - '*'
          - Sid: AllowPutEventSpokeEventBus 
            Effect: Allow
            Action: 
              - events:PutEvents
            Resource:
              - !Sub "arn:aws:events:${AWS::Region}:${HubAccount}:event-bus/${HubEventBusName}"


